language: bash

os:
- linux
- osx

addons:
  apt:
    packages:
    - mono-complete

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mono; fi
- curl https://sh.rustup.rs -sSf -o rustup.rs
- chmod ugo+x rustup.rs
- ./rustup.rs -y
- source "$HOME/.cargo/env"
- rm rustup.rs

script:
- ./build/car_setup.sh
- ./test/c_lang.c
- ./test/c#_lang.cs
- ./test/c++_lang.cc
- ./test/c++_lang.cpp
- ./test/go_lang.go
- ./test/java_lang.java
- ./test/rust_lang.rs

deploy:
  provider: releases
  api_key: 93dc5c91526cf7f58900b038af12c91db57e54ce
  file: ./build/car_setup.sh
  skip_cleanup: true
  on:
    tags: true
