language: bash

before_install:
- sudo apt-get clean
- sudo apt-get update -qq
- sudo apt-get install -qq -y mono-complete
- curl https://sh.rustup.rs -sSf -o rustup.rs
- chmod ugo+x rustup.rs
- ./rustup.rs -y
- source "$HOME/.cargo/env"
- rm rustup.rs

script:
- mkdir bin
- cp ./src/car.sh ./bin/car
- chmod 755 ./bin/car
- PATH="$PWD/bin:$PATH"
- ./test/c_lang.c
- ./test/c#_lang.cs
- ./test/c++_lang.cc
- ./test/c++_lang.cpp
- ./test/go_lang.go
- ./test/java_lang.java
- ./test/rust_lang.rs

os:
- linux
- osx
